---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: honyabookstore-dev-backend
resources:
  - ../../../base/backend/honyabookstore/
  - ./httproute.yaml
patches:
  - path: ./deployment.patch.yaml
  - path: ./honyabookstore.secret.patch.sops.yaml
  - path: ./keycloak.secret.patch.sops.yaml
images:
  - name: ghcr.io/honya-bookstore/backend
    digest: sha256:6023e4e7ee105511f1e1ccb3bb4a9f95f7aad28d3e23b0748fdb2f1a325a62d5
