---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: honyabookstore-dev-backend
resources:
  - ../../../base/backend/honyabookstore/
  - ./httproute.yaml
patches:
  - path: ./deployment.patch.yaml
  - path: ./honyabookstore.secret.patch.sops.yaml
  - path: ./keycloak.secret.patch.sops.yaml
images:
  - name: ghcr.io/honya-bookstore/backend
    digest: sha256:c07c72564340d0342500d638d3e7ca3073aa956e5e00ad0298e4b8c3ae2aaf57
