---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: honyabookstore-dev-backend
resources:
  - ../../../base/backend/honyabookstore/
  - ./httproute.yaml
patches:
  - path: ./deployment.patch.yaml
  - path: ./honyabookstore.secret.patch.sops.yaml
  - path: ./keycloak.secret.patch.sops.yaml
images:
  - name: ghcr.io/honya-bookstore/backend
    digest: sha256:82c4f0ec1f5287c5ce991e956222038021438528319f6a7e87cff40a3b8dd5fc
