variable "keycloak_url" {
  type = string
}

variable "terraform_client_secret" {
  type        = string
  sensitive   = true
  description = "The secret for clients with an access_type of CONFIDENTIAL or BEARER-ONLY. This value is sensitive and should be treated with the same care as a password. If omitted, this will be generated by Keycloak."
}

variable "backend_client_secret" {
  type        = string
  sensitive   = true
  description = "The secret for clients with an access_type of CONFIDENTIAL or BEARER-ONLY. This value is sensitive and should be treated with the same care as a password. If omitted, this will be generated by Keycloak."
}

variable "frontend_client_secret" {
  type        = string
  sensitive   = true
  description = "The secret for clients with an access_type of CONFIDENTIAL or BEARER-ONLY. This value is sensitive and should be treated with the same care as a password. If omitted, this will be generated by Keycloak."
}

variable "frontend_root_url" {
  type        = string
  default     = ""
  description = "When specified, this URL is prepended to any relative URLs found within valid_redirect_uris, web_origins, and admin_url. NOTE: Due to limitations in the Keycloak API, when the root_url attribute is used, the valid_redirect_uris, web_origins, and admin_url attributes will be required"
}

variable "frontend_base_url" {
  type        = string
  default     = "/"
  description = "Default URL to use when the auth server needs to redirect or link back to the client"
}

variable "frontend_web_origins" {
  type        = list(string)
  default     = ["*"]
  description = "A list of allowed CORS origins. To permit all valid redirect URIs, add +. Note that this will not include the * wildcard. To permit all origins, explicitly add *"
}

variable "frontend_valid_redirect_uris" {
  type        = list(string)
  default     = ["*"]
  description = "A list of valid redirect URIs for the client. Wildcards are permitted"
}

variable "frontend_admin_url" {
  type        = string
  default     = "/"
  description = "URL to the admin interface of the client"
}

variable "swagger_web_origins" {
  type        = list(string)
  default     = ["*"]
  description = "A list of allowed CORS origins. To permit all valid redirect URIs, add +. Note that this will not include the * wildcard. To permit all origins, explicitly add *"
}
